name: Test action
on:
  pull_request:
    types: [labeled, unlabeled]
      
jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
    - name: Hello world action step
      id: hello
      uses: docker://mabead/old-github-packages-cleaner:latest
      with:
          who-to-greet: 'Max'